### ISSUE TITLE
`add-ssh-key` / `create-ssh-key` command

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/clever-tools#1]
That would help people not proficient with SSH key handling.

**Comment by urcadox** [comment]
Seems like a good idea. I guess the main questions would be how far should we go on the `create-ssh-key` command (directly call ssh-keygen with default parameters or let the user choose some stuff) and how far would we have to go to make this useable on Windows?

**Comment by divarvel** [comment]
The CLI tool will soon use HTTPs auth for git
