### ISSUE TITLE
Display human readable names instead of UUID

### ISSUE THREAD

**Issue by caillef** [CleverCloud/clever-tools#102]

**Comment by divarvel** [comment]
Do you want to implement it @caillef?

**Comment by caillef** [comment]
Yes, will it be only used when you want to link your application or aliases will be removed ?

**Comment by divarvel** [comment]
Instance ids are not displayed in the console yet. In order to use human-readable names, we have to list instances first. Maybe in `clever status`?

**Comment by hsablonniere** [comment]
@divarvel @caillef What do we do with this? I'm not sure what is the need.

**Comment by divarvel** [comment]
I think this issue can be safely closed, as long as clever-tools doesn't display instance ids.
