### ISSUE TITLE
The cli doesn't check if we are connected before trying to get the logs

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-tools#11]
In ``src/models/logs.js:75``, trying to call ``.reverse()`` on an object ``{"id": xxx, "message": "Not connected"}`` leads to an ``undefined is not a function``

Also, ``logs`` command might not be the only one missing the "authentication" check

**Comment by divarvel** [comment]
Authentication for almost all operations is handled by clever-client iirc.
The events API is purely WS and connection errors are handled by closing the connection, so it's not a problem as well.
The logs API is not handled by clever-client, hence the issue. It has to be fixed in the log handler.
