### ISSUE TITLE
Error at deploy if remote already exists in git

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-tools#111]
My use case was the following:

I cloned a repo with a `.clever.json` and added a remote `prod` via git.
When I pulled the repo at some point, the `.clever.json` file was updated and a new remote `prod` was added in it but with a different remote url.

`clever deploy` gave me the following error: `[ERROR] The "prod" remote already exist and does not point to <url>`

So, if the remote already exists in git, should we create a temporary remote to push to or simply display a message asking the user to remove its git remote ?

I would prefer the temporary remote if possible, sometimes I manually push without noticing it.

**Comment by divarvel** [comment]
So:

- if no remote exists => create it and use it
- if a remote already exists => print a warning and use a temporary

The persisting remote is useful for knowing which commit is deployed, but also for speeding up deployments so I think it's a good thing to try to use it every time.
I'll check what's possible with nodegit and temporary remotes
