### ISSUE TITLE
clever deploy: display a better message when the user tries to push an already up-to-date repository 

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-tools#118]
Usually, people using `clever deploy` want to restart their app, but it won't trigger a deployment. What they really want is `clever restart`. We should display something like "nothing to push, do you want to `clever restart` ?"

**Comment by divarvel** [comment]
@BlackYoup  see 53f5edfda9b0e0f16efce169af61b54cd5f6e9d9
