### ISSUE TITLE
Add an option to deploy a particular commit instead of HEAD

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-tools#132]
I'm in a case where I need to push a particular commit and not the HEAD of the branch, and it doesn't seem to have an option to specify a commit or maybe even a particular tag ?

**Comment by hsablonniere** [comment]
From what I'm reading in the code, we're getting the the current commit id of the specified branch (or current branch by default). Then we push this branch to the remote master.

Would this work if we did something like that?

`git push a42e73df:refs/heads/master`

**Comment by BlackYoup** [comment]
Without testing it, I think that's what we want to do, yes

**Comment by hsablonniere** [comment]
libgit and thus nodegit cannot push a specific commit (without creating a branch/tag).

https://github.com/libgit2/libgit2/issues/3178

This is forcing us to discard this feature/enhancement request (for now).
