### ISSUE TITLE
`console.debug` eats logging output in node 8

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/clever-tools#134]
Before node 8, `console.debug` did not exist, so the logger defaulted to `console.log`.
In node 8, `console.debug` exists, but does not log its arguments (I guess it can be done with an env variable or something).

It's not documented yet (https://t.co/JHrEGE3kT3),  so I don't know how to tell it to display logs when `CLEVER_VERBOSE` is set.

**Comment by BlackYoup** [comment]
It seems like this method is not yet implemented by Node. See https://github.com/nodejs/node/issues/12675

**Comment by hsablonniere** [comment]
OK so about `console.debug`:

* No present in 7 https://nodejs.org/docs/latest-v7.x/api/console.html
* Present but not documented in 8 https://nodejs.org/docs/latest-v8.x/api/console.html
* Present AND documented in 9 https://nodejs.org/docs/latest-v9.x/api/console.html#console_console_debug_data_args

**Comment by BlackYoup** [comment]
From the documentation, `console.debug()` seems to be an alias to `console.log()` in node 9, I'm not sure it's relevant to use it.

**Comment by divarvel** [comment]
I think we should not rely on inspecting the `console` object and use only `console.log` and `console.error`.

**Comment by hsablonniere** [comment]
I'm on it, I'll also refactor stuffs a bit ;-)
