### ISSUE TITLE
"This application dosen't belong to you" When the app is not in your organisation ?

### ISSUE THREAD

**Issue by leonard-IMBERT** [CleverCloud/clever-tools#15]
J'ai mon application: 
```
Application Thoth-Principal
  alias: thoth-principal
  id: app_5d0c9306-0758-46bf-9e9f-45545773181a
  deployment url: git+ssh://git@push.par.clever-cloud.com/app_5d0c9306-0758-46bf-9e9f-45545773181a.git
```
Bien qu'etant admin de l'organisation, quand je demande un `clever status` ou un `clever env`, j'ai le droit a `[ERROR] The provided application id doesn't belong to you [4002]`
Une idee ?

**Comment by urcadox** [comment]
Can you translate your issue to English so more people can understand you?

Also, could you paste your .clever.json file (located at the root of your app)?

**Comment by leonard-IMBERT** [comment]
Sorry for the language mistake,
I have an application wich appear like that in `clever list`:
```
Application Thoth-Principal
  alias: thoth-principal
  id: app_5d0c9306-0758-46bf-9e9f-45545773181a
  deployment url: git+ssh://git@push.par.clever-cloud.com/app_5d0c9306-0758-46bf-9e9f-45545773181a.git
```
I'm an admin in the organisation and when i try to run the most of the command, i got `[ERROR] The provided application id doesn't belong to you [4002]`

My .clever.json correspond to: 
```json
{
  "apps":[
  {
    "app_id":"app_5d0c9306-0758-46bf-9e9f-45545773181a",
    "deploy_url":"git+ssh://git@push.par.clever-cloud.com/app_5d0c9306-0758-46bf9e9f-45545773181a.git",
    "name":"Thoth-Principal",
    "alias":"thoth-principal"
   }
 ]
}
```
any idea ?

**Comment by divarvel** [comment]
When was the application linked? Can you try to remove it from `.clever.json` and add it again? If it still doesn't have `orga_id` after that, then it's a problem with the API.

**Comment by leonard-IMBERT** [comment]
I just delete the .clever.json, relink and it's working now. Effectively, an `orga_id` appear in the .clever.json. thanks !
