### ISSUE TITLE
Publish deb package

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/clever-tools#153]

**Comment by hsablonniere** [comment]
We already have a job building the artifact but it seems broken.
We need a step in the job to publish the package on bintray or something...

**Comment by hsablonniere** [comment]
OK, so the job is working! It's just that you cannot install a deb package that does not start with a digit. You can force it with this:

```
dpkg --force-bad-version -i the-package.deb
```

We need to push in bintray!
