### ISSUE TITLE
Add a command to show the current logged user profile

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-tools#161]
It would tell the user some information about its account, maybe: name, email, 2FA status (and a link to the console to enable it if it's not ?)

For example, npm uses `npm profile` to get the user's profile

**Comment by hsablonniere** [comment]
Yep, looks like this:

![capture d ecran_2018-01-03_15-08-19](https://user-images.githubusercontent.com/236342/34523542-354c9cb0-f098-11e7-8f31-f45b922a5296.png)

Do we have those infos?

**Comment by divarvel** [comment]
`GET /self` (https://www.clever-cloud.com/doc/api/#!/self/getSelf)
Gives this
```


{
  "address": "string",
  "admin": "boolean",
  "avatar": "string",
  "canPay": "boolean",
  "city": "string",
  "country": "string",
  "creationDate": "timestamp",
  "email": "string",
  "emailValidated": "boolean",
  "hasPassword": "boolean",
  "id": "string",
  "lang": "string",
  "name": "string",
  "oauthApps": [
    "string"
  ],
  "phone": "string",
  "preferredMFA": "string",
  "zipcode": "string"
}
```

**Comment by divarvel** [comment]
`preferredMFA` is `TOTP` (or `SMS` IIRC).

**Comment by BlackYoup** [comment]
Also, `preferredMFA` is null if there is no 2FA and to enable 2FA, it's over here https://console.clever-cloud.com/users/me/authentication

**Comment by hsablonniere** [comment]
OK, so only those 3 infos for now in a table just like NPM?

**Comment by divarvel** [comment]
We don't use tables anywhere for now, so I think simple text would be enough (see `clever status` for instance)

**Comment by hsablonniere** [comment]
OK, perfect, I'll put some tabs for the alignement: KISS!
