### ISSUE TITLE
Add option on `clever ssh` for custom ssh config

### ISSUE THREAD

**Issue by nfilzi** [CleverCloud/clever-tools#164]
From what I understood, `clever ssh` uses by default the `id_rsa` one.
Would be nice to have a way to give an option to make it use my custom clever ssh config.

That's all! Thanks for your time folks! 👋

**Comment by divarvel** [comment]
Hi `clever ssh` directly calls `ssh`, so it should pick up your default ssh config. (eg in `~/.ssh/config`)

**Comment by hsablonniere** [comment]
OK, so on this matter we have 2 solutions:

* provide a new CLI option to be passed to the ssh command
* let the users configure their specific clever key (this means that we should document it a bit somewhere)

**Comment by divarvel** [comment]
I think it should be nice to be quickly able to configure the key without having to fiddle with `.ssh/config` (personally, I hate having to do that for git). So a `-i path/to/key` argument would be nice. For more complex config, users can still use `~/.ssh/config`, but the "different ssh key" usecase is common enough IMO
