### ISSUE TITLE
App dependencies environment variables are not included in `clever env`

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/clever-tools#165]
It only fetches addons' env vars.

**Comment by hsablonniere** [comment]
What's the correct approache here? Do we need to list the dependencies and then list the env vars from each of them?

**Comment by divarvel** [comment]
I've added an enpoint which lists all the environment variables listed by dependencies, let me check if it's available

**Comment by divarvel** [comment]
It's not available yet. An intermediate solution would be indeed to list all app dependencies and fetch env vars for each application

**Comment by divarvel** [comment]
There is a new resource to get all the environment variables exposed by application dependencies https://www.clever-cloud.com/doc/api/#!/self/self_applications_appId_dependencies_env_get

**Comment by divarvel** [comment]
Fixed by #169
