### ISSUE TITLE
Remove update-notifier and provide something else to notify about new releases

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#188]
## Context

Because we chose to stop doing npm release and prevent usage of `npm install -g` of the tools, the `update-notifier` behaviour was broken.

We need a solution to notify users that a new version of the clever-tools is available.

## TODO

* [x] Fork `update-notifer` so we it can rely on public remote list of tags (GitHub or Gitlab API) instead of npm releases.
* [x] Use this new package.

**Comment by divarvel** [comment]
oh, right.

**Comment by hsablonniere** [comment]
If we fork update-notifier, we could just change it so it accepts a custom `latestVersion` fetcher ?

https://github.com/yeoman/update-notifier/blob/master/index.js#L101

https://www.npmjs.com/package/latest-version
