### ISSUE TITLE
Add ⚠️ message when deploying a non-existent branch

### ISSUE THREAD

**Issue by k33g** [CleverCloud/clever-tools#195]
eg:
```shell
clever deploy --branch my-killer-feature
```

```shell
😡 this 🌿 doesn't exist
```

**Comment by hsablonniere** [comment]
Before:

![capture d ecran_2018-03-07_11-51-12](https://user-images.githubusercontent.com/236342/37088520-f0aad08a-21fd-11e8-8881-8410b801bc01.png)

NOTE: Process exit code is `0`

After:

![capture d ecran_2018-03-07_11-51-25](https://user-images.githubusercontent.com/236342/37088534-fb1869b0-21fd-11e8-9818-db3e111b3035.png)

NOTE: Process exit code is `1`
