### ISSUE TITLE
Error on `clever deploy` command exit code was 0 

### ISSUE THREAD

**Issue by FGRibreau** [CleverCloud/clever-tools#197]
```
$ ./clever deploy
[ERROR] { Error: error authenticating: no auth sock variable errno: -1 }
```

Added [this code](http://blog.fgribreau.com/2018/02/continuous-deployment-on-clevercloud.html) to a new project, `clever deploy` did exit with `0`, I think it should not, am I right?

**Comment by hsablonniere** [comment]
This is actually something I worked on today.
Can you tell me what you did to cause this error?
I'll have a fix soon...

**Comment by FGRibreau** [comment]
In fact, no build pass anymore, I just do this on a deploy step on gitlab :

```sh
  script:
    - apt-get update && apt-get install -y curl
    - curl https://clever-tools.cellar.services.clever-cloud.com/releases/latest/clever-tools-latest_linux.tar.gz > clever-tools-latest_linux.tar.gz
    - tar -xvf clever-tools-latest_linux.tar.gz
    - ./clever login --token $CLEVER_TOKEN --secret $CLEVER_SECRET
    - ./clever link $APP_ID
    - ./clever deploy
```

**Comment by hsablonniere** [comment]
I think I misread your description.
When `clever deploy` fails, it will exit with `1` instead of `0` in the next release.

It seems like you have a problem with your SSH token/secret config.
Let me know when we can discuss those details...

**Comment by FGRibreau** [comment]
Yes, it seems related to SSH and that's another issue indeed, at least `clever deploy` should fail (and it did not, it only logged "[ERROR] ...")

**Comment by hsablonniere** [comment]
OK.
Let's focus this issue on the exit code. I'll close it when the fix is released.

Can you file another issue for your auth sock problem?
With `clever deploy -v`, you may have more details to give us in this new issue.

**Comment by FGRibreau** [comment]
\o/

**Comment by FGRibreau** [comment]
Concerning the issue `Error: error authenticating: no auth sock variable errno: -1`, I fixed it by removing (if it exist) a previous .clever.json and specifying explicitly the app alias

```yaml
    - apt-get update && apt-get install -y curl
    - curl https://clever-tools.cellar.services.clever-cloud.com/releases/latest/clever-tools-latest_linux.tar.gz > clever-tools-latest_linux.tar.gz
    - tar -xvf clever-tools-latest_linux.tar.gz
    - ./clever login --token $CLEVER_TOKEN --secret $CLEVER_SECRET
    - rm -f .clever.json
    - ./clever link -a deploy $APP_ID
    - ./clever deploy -a deploy
```
