### ISSUE TITLE
`clever deploy` on already pushed commit

### ISSUE THREAD

**Issue by KannarFr** [CleverCloud/clever-tools#198]
## Context

Hi,

If a commit B had been pushed and deployed. Then a A commit which is older than B is redeployed from Console. And finally `$ clever deploy` to redeploy A. There is an error message specifying that the current clever application is up-to-date:                                                                                                                                                                     

`[ERROR] The clever-cloud application is up-to-date. Try 'clever restart' to restart the application`

We should edit the message or create an interaction to specify the last most recent commit by default.

## TODO

* [ ] When `clever deploy` fails and advise to do a `clever restart` it should mention the commit id if it's necessary.

**Comment by divarvel** [comment]
We should improve the message, but it already (correctly) informs the user that `clever restart` is probably what they want.

**Comment by KannarFr** [comment]
Yup we had a talk with @hsablonniere and @BlackYoup and we think that fill a `--commit <commit-id>` with the most recent commit can be the goal of this issue.

**Comment by divarvel** [comment]
Please don't wait for user input if the user hasn't explicitely asked for interactivity

**Comment by KannarFr** [comment]
Then we just have to improve the message specifying that `--commit <commit-id>` exists.

**Comment by hsablonniere** [comment]
@KannarFr OK for just adding the `--commit <commit-id>`. Description updated :+1:
