### ISSUE TITLE
`clever open` always opens in http:// (not secured)

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#221]
Do we have a way to know if we can open directly in HTTPS?

**Comment by divarvel** [comment]
Not currently. It will be possible when we integrate TLS redirect options
(in the load balancer for instance)

For now we rely on the application handling redirection itself

**Comment by hsablonniere** [comment]
Now that we have auto Let's Encrypt and now that HTTPS becomes ubiquitous, I think we can open HTTPS by default.

**Comment by divarvel** [comment]
:+1:
