### ISSUE TITLE
command exits 0 even if [ERROR] occurs

### ISSUE THREAD

**Issue by Nigui** [CleverCloud/clever-tools#226]
I'm creating a bash script using `clever` commands.

I want to test if command ends well or not (i.e. exits with error code 0 or + ).

For exemple, with this script : 

```bash
#!/bin/bash

clever link anapp 

if [ $? -eq 0 ]
then
  echo "Success"
else
  echo "Fail" >&2
fi
```

outputs : 

```
[ERROR] Application not found
Success
```

Event if I haven't `anapp ` app on clever cloud.

It means that `clever link ...` does not exit with a code > 0 when error occurs. 

You can replace `clever link`by any other command.

**Comment by Nigui** [comment]
For the ones interested, I'm bypassing with : 

```bash
#!/bin/bash

out=$(clever link anapp 2>&1)

if [ $out =~ "Error" ]
then
  echo "Fail" >&2
else
  echo "Success"
fi
```

**Comment by hsablonniere** [comment]
Hey @Nigui, we're about to release a big refactor that really exits with Linux error codes. I'm closing this issue and I'll let you follow this one: https://github.com/CleverCloud/clever-tools/issues/202
