### ISSUE TITLE
Use credentials from environment variables

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#240]
When using the CLI in scripting environments, you need to manually login with the creds as arguments.

We could automatically try to use the credentials if they are present as environment variables for all commands.

cc @k33g

**Comment by hsablonniere** [comment]
This is actually very easy to implement in [configuration.js](https://github.com/CleverCloud/clever-tools/blob/master/src/models/configuration.js).

I propose `CLEVER_TOKEN` and `CLEVER_SECRET`.

The question is: if you have a config AND env vars, which one do we use?

1. We use env vars when available (even if config file contains values)
2. We use config file (even if env vars are set)

**Comment by hsablonniere** [comment]
I prefer 1. env vars > config file

**Comment by hsablonniere** [comment]
Interesting... It means the warning would be displayed for each command.

**Comment by urcadox** [comment]
I guess env vars will only ever be used in scripts / CI so a warning for each command should not be problematic.

**Comment by divarvel** [comment]
In CI, there should not be a config file anyway, so no warning. For
scripts, it's a bit different, I can indeed see it become annoying

**Comment by hsablonniere** [comment]
@divarvel Currently people use `clever login --token XXX --secret YYY` in CI with env vars. So they have a config file at some point.

**Comment by divarvel** [comment]
Why use clever login at all if token and secrets can be provided through
env vars? In this form, clever-login's only purpose is to create a file
