### ISSUE TITLE
Re-enable npm release ?

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#241]
Now that we're about to remove our nodegit dep in #236, we could consider going back to releasing the tools as an npm package.

Why?

* Without nodegit, the support for this will be much simpler
* Lots of user would like that!!

What should we do?

* Amend the tag job to release automatically to npm
* Put back the dependency we used to warn about updates

**Comment by ptitfred** [comment]
Do you consider keeping the tar balls?

**Comment by hsablonniere** [comment]
@ptitfred We'll keep them. The automation is already there, some clients (including you maybe) are using this with a simple wget/curl in scripts so I think it's still relevant..

**Comment by fmenou** [comment]
Yes I do. And I just noticed 0.9.3 is not available anymore. I will upgrade, but is that normal?

**Comment by fmenou** [comment]
> And I just noticed 0.9.3 is not available anymore.

It looks like it was transient, it's back, nevermind.

**Comment by hsablonniere** [comment]
The NPM publish build is done! :tada:

We haven't released a stable version yet but a beta version is available.
