### ISSUE TITLE
Open the Clever Cloud Console with a command

### ISSUE THREAD

**Issue by cnivolle** [CleverCloud/clever-tools#247]
This command would be like `clever open` but for the web console, not the URL of the application itself.
I was wondering if this kind of command could be useful to anyone, other than me.

The usage would be quite simple: 
Open the web console directly to the app's informations, with a command like `clever console` (maybe with using the option `--alias` to route to the correct app URL).

I'm open to anything smarter than `clever console`.

**Comment by divarvel** [comment]
+1 that sounds reasonable.

`clever console [--alias <alias>]` is great

Le jeu. 9 août 2018 15:41, Clément Nivolle <notifications@github.com> a
écrit :

**Comment by hsablonniere** [comment]
Fixed by @grallc!! Thanks again :tada:
As I mentioned this feature will be shipped with the new release.
It may take a bit of time still.

**Comment by hsablonniere** [comment]
@grallc Your feature is present in the beta versions ;-)
