### ISSUE TITLE
Add an option so `clever deploy` can do a `clever restart` automatically if remote commit is the same

### ISSUE THREAD

**Issue by jygastaud** [CleverCloud/clever-tools#276]
Actually, if you want to deploy the same commit twice, even with `-f` option, the command will return an error `[ERROR] The clever-cloud application is up-to-date. Try this command to restart the application: clever restart`.

Without `force` option, `restart` sounds like fine.
However `deploy` with `--force` option should still be OK.

Current use case is : deploying from Gitlab-CI, triggering manual action that will rebuild the website and run every CC HOOKS.

**Comment by hsablonniere** [comment]
Interesting...

So right now here's the output:

```bash
$ clever deploy
[ERROR] The clever-cloud application is up-to-date. Try this command to restart the application:
        clever restart
```

```bash
$ clever deploy --force
[ERROR] The clever-cloud application is up-to-date. Try this command to restart the application:
        clever restart
```

It seems like you don't want to change the situation for `clever deploy` but you expect a different behaviour from `clever deploy --force`. I see two possibilities:

1. A bit like what a `git push` would do: we just log that everything is up to date without any errors.
2. Forcing the deploy would mean you want to automatically trigger a restart if the remote is already up to date.

This seems simple but I think it requires some thinking...

**Comment by jygastaud** [comment]
> It seems like you don't want to change the situation for clever deploy
true

About the possibilities, it's more the `2` that I expect.

As a side note, `--force` option before `1.0.0` has the same behavior of `git push --force`.
Looks like it's not the case anymore.

**Comment by BlackYoup** [comment]
IIRC, we used the same behavior that git has . `clever deploy --force` == `git push --force`. If there is nothing to push, no deployment is started and if you want to restart, you have to use the `clever redeploy` command.

**Comment by hsablonniere** [comment]
Here's what you have with version 0.10.1:

```bash
$ clever-old deploy       
Pushing source code to Clever Cloud.
[ERROR] The clever-cloud application is up-to-date. Try `clever restart` to restart the application
```

exit status: 0

```bash
$ clever-old deploy -f
Pushing source code to Clever Cloud.
[ERROR] The clever-cloud application is up-to-date. Try `clever restart` to restart the application
```

exit status: 0

We "just" fixed the fact that logging an error should also return an exit status code 1 and log to stderr.

**Comment by jeremybastin1207** [comment]
Hi,

Any update on this issue ? It would be really useful to deploy twice on the same commit.

**Comment by jeremybastin1207** [comment]
Hi @hsablonniere,
Thanks for this detailed report. The command "clever deploy --force --same-commit-policy=rebuild" fullfills my need to re-deploy on the same commit with a rewritten git history.

**Comment by hsablonniere** [comment]
@jeremybastin1207 Thank you for your feedbacks. Sorry for the holiday delay :p
