### ISSUE TITLE
Release 1.0.2 link seems to not working

### ISSUE THREAD

**Issue by kriyss** [CleverCloud/clever-tools#286]
Hi, I use clever-tools to perform deployment trough *gitlab-ci*. Since version `1.0.2` came up, the command `clever link` seems to do nothing. There is no effect on clever-cloud, no error message, no error code.

Work perfectly with `1.0.0` and `1.0.1`.

## Path to reprocude : 

```shell
export CLEVER_ORGANIZATION_ID=[ORG_ID]
export APP_SLUG=[APP_SLUG]
export CLEVER_TOKEN=[YOUR_TOKEN]
export CLEVER_SECRET=[YOUR_SECRET]
export CLEVER_VERSION=1.0.2

curl -0 https://clever-tools.cellar.services.clever-cloud.com/releases/"$CLEVER_VERSION"/clever-tools-"$CLEVER_VERSION"_linux.tar.gz > clever-tools-tar.gz
tar xvzf clever-tools-tar.gz --strip-components=1

./clever login --token $CLEVER_TOKEN --secret $CLEVER_SECRET
./clever link --org $CLEVER_ORGANIZATION_ID $APP_SLUG --alias $APP_SLUG
```

## Tested on :

- Arch
- Ubuntu 
- Docker

Thanks you.

**Comment by guyzmo** [comment]
same issue for me, thanks to @kriyss I was not surprised when I got hit by that bug ☺

**Comment by hsablonniere** [comment]
Thanks @kriyss and @guyzmo, I'm trying to find out what happened. We'll release a fix ASAP. Sorry.

**Comment by hsablonniere** [comment]
Fixed in https://github.com/CleverCloud/clever-tools/blob/1.1.0/CHANGELOG.md#110-2018-10-30
