### ISSUE TITLE
Bug on `clever deploy` from subdirectory

### ISSUE THREAD

**Issue by KannarFr** [CleverCloud/clever-tools#292]
Hi,

I tried to run `clever deploy` from subdirectory of my repository but had this error:

`[ERROR] Cannot read property 'split' of null`

After adding some logs I had:

```
{ ResolveRefError: Could not resolve reference "HEAD".
    at Function.resolve (/home/kannar/git/cc/clever-tools/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:1638:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  name: 'ResolveRefError',
  code: 'ResolveRefError',
  data: { ref: 'HEAD' },
  message: 'Could not resolve reference "HEAD".',
  caller: 'git.currentBranch' }
```

**Comment by hsablonniere** [comment]
I think we assume the `.git` folder is in the current working directory.

@KannarFr How do you think we should solve this?

Going up recursively in the file tree would be the simple answer but I'm concerned with security. I guest we could go up like we do to find the `.clever.json` and stop once we find one.

**Comment by urcadox** [comment]
I don't see how it could be problematic security wise, it's most likely what Git does btw.

I was pretty sure I already implemented this feature when we were using nodegit but I guess it was the .clever.json stuff actually.

**Comment by divarvel** [comment]
nodegit did that automatically, if I remember correctly.
The feature was indeed for .clever.json

**Comment by KannarFr** [comment]
@hsablonniere I agree about recursively find the `.clever.json` file.

**Comment by KannarFr** [comment]
@hsablonniere it's fixed now right?

**Comment by hsablonniere** [comment]
@KannarFr Indeed
