### ISSUE TITLE
Deployment doesn't start if git repository is a shallow copy

### ISSUE THREAD

**Issue by paulrbr-fl** [CleverCloud/clever-tools#293]
This issue is more of an "open discussion" request.

## The set

Deployments often happen automatically via continuous integration build machines. Those build machine can often fetch "shallow" copies of the application to be deployed (usually via a `git clone/fetch --depth=10`).

## The issue

Currently `clever` CLI tools fails when trying to deploy from a shallow repository with the following error:
```
> clever deploy --alias my-awesome-app --force                                                                                                                                                                          
Pushing source code to Clever Cloud.                                                                                                                                        
[ERROR] Failed to read git object with oid 9097f31f10f72408d3d396e9ec92dbce0956c2c8
```

_Note: It doesn't work neither without the `--force` flag_

## The potential fixes

Here are a few ideas:
- Explain to users (via doc / clear error message) that an `unshallow` git repo is needed to deploy
- Do the `git fetch --unshallow` within the `clever` CLI "hiding" (or maybe warning) it to the user
- other?

**Comment by clementd-fretlink** [comment]
-1 for an implicit `git fetch --unshallow`
+1 for explaining both in the doc and an error message that a full clone is needed (the error message can mention `git fetch --unshallow`

**Comment by urcadox** [comment]
Doing a git fetch without the user knowing does not seems like a good idea to me either.

Explaining what [is / may be] happening to the user when this error occurs seems fine to me.

**Comment by clementd-fretlink** [comment]
also, obligatory reference

![](https://media.npr.org/assets/img/2018/09/27/rev-1-asib-trl-9090r_high_res_jpeg-1-_wide-3afaaddfb18a9a5732dbd6843e417c693a5949fb-s1100-c15.jpeg)

**Comment by hsablonniere** [comment]
@paulrbr-fl Thanks for the feedback :smile: 
@clementd-fretlink @urcadox Agreed :+1:

TODO:

* [ ] Mention this problem in the docs
* [ ] Improve error message

_NOTE: This issue will be closed once this TODO is done_

**Comment by KannarFr** [comment]
@hsablonniere Bump and notice that `git fetch --prune --unshallow` can be better.

**Comment by hsablonniere** [comment]
I did some research and it's not that trivial to detect if a repo is shallow and isomorphic-git does not seem to have anything on this.

@Keruspe do you have an opinion? I saw that reading `.git/shallow` could be a way to do it. WDYT?

**Comment by Keruspe** [comment]
Isomorphic-got should replace all of its oid === '00000000000000000000' by something like « isRootCommit » which checks that either it’s the null commit, or the oid is in .git/shallow

**Comment by hsablonniere** [comment]
For reference: https://github.com/git/git/blob/172e8ff696ea0ebe002bdd1f61a3544fc7f71a61/shallow.c#L55

**Comment by hsablonniere** [comment]
I tried something that could be helpful while we wait for a better solution:

* Try push
* If it fails, try a naive `isShallow()` based on the presence of `.git/shallow`
  * If `isShallow()` is true => display a message with maybe a link to a detailed guide about this
  * If `isShallow()` is false => throw error from push

This way, in situations where the repo is shallow but where objects needed to be pushed are here, it will work.

**Comment by hsablonniere** [comment]
In parallel, we create an issue over at isomorphic-git to implement a real `isShallow` or maybe an internal check in push to get a detailed error.

If and when this is ready, we update.

**Comment by hsablonniere** [comment]
https://github.com/isomorphic-git/isomorphic-git/issues/1187

**Comment by hsablonniere** [comment]
https://gitlab.com/help/ci/pipelines/settings.md#git-shallow-clone

**Comment by hsablonniere** [comment]
Released in https://github.com/CleverCloud/clever-tools/releases/tag/2.7.0 https://github.com/CleverCloud/clever-tools/blob/master/CHANGELOG.md#270-2020-08-20

**Comment by paulrbr-fl** [comment]
Thanks for this!

**Comment by hsablonniere** [comment]
@Keruspe suggest that we could have an `--auto-unshallow` on `clever deploy` that would do a `git fetch --unshallow` on the default remote. :thinking:
