### ISSUE TITLE
Allow having a "default" alias

### ISSUE THREAD

**Issue by Keruspe** [CleverCloud/clever-tools#30]
For now, let's say I have a prod and a preprod app.

```
clever link prod_id
clever link preprod_id --alias preprod
```

I would expect "clever" to deal with prod, and "clever --alias preprod" to deal with preprod.

Currently "clever" complains that I do not pass it an alias, which has been autogenerated as equal to the app name

**Comment by urcadox** [comment]
I am in favor of adding a `default` flag or a `default_app` property in `.clever.json` when we first link an app (and/or when creating a second link).

**Comment by divarvel** [comment]
I'm more inclined to add a default app property and a way to make an application as the default one,
but not doing so automatically.
