### ISSUE TITLE
Asking for non existing logs keeps the fetching process running endlessly

### ISSUE THREAD

**Issue by noisegrrrl** [CleverCloud/clever-tools#304]
When logs don't exist (for instance if asking for logs older than 5 days) the cli is stuck saying waiting for application logs and never gives back control to the user.

**Comment by KannarFr** [comment]
Maybe it can be useful to use the logs retention duration. The LogsAPI has HTTP GET `/v2/logs/retention` endpoint without authentication. It returns `{ "durationInDays": x}` with `x` an Integer.

**Comment by KannarFr** [comment]
More, the retention duration in days includes the current days. So if we are the 16th February, with a logs retention of 3 days, the availables indexes are the 16th, 15th, 14th February.

**Comment by hsablonniere** [comment]
FYI, this was a more general bug: whatever the options, the command would never give back the process.
