### ISSUE TITLE
Error when trying to deploy from subdirectory

### ISSUE THREAD

**Issue by RudyBaer** [CleverCloud/clever-tools#305]
I don't know if it's a real bug but @KannarFr told me to report it.

To replicate :

Create folder with git init
then create a subfolder and link clever app
When I run clever deploy I get a error message

`[ERROR] Cannot read property 'split' of null`
 
I think it's just a missing control when .git folder is missing or on parent directory

**Comment by mickaelchanrion** [comment]
The issue has been fixed in the v1.6.1

**Comment by hsablonniere** [comment]
@mickaelchanrion Thx, I forgot to mark this in the rush.
