### ISSUE TITLE
Clever activity fails when stdout is not a tty

### ISSUE THREAD

**Issue by haitlahcen** [CleverCloud/clever-tools#306]
The function `moveCursor` from `process.stdout.moveCursor` is undefined when `stdout` is not a tty:

`TypeError: process.stdout.moveCursor is not a function\n    at clearPreviousLine (/snapshot/clever-tools_1.3.0/src/commands/activity.js:62:18)`

This behavior can be reproduced with:
`node -p -e "process.stdout.moveCursor(0, -1)" `
`node -p -e "process.stdout.moveCursor(0, -1)" | cat`

Fortunately, node is exposing a `isTTY` [attribute](https://nodejs.org/api/tty.html#tty_tty)

**Comment by clementd-fretlink** [comment]
Indeed, that's on me.
