### ISSUE TITLE
Add something like "clever aliases"

### ISSUE THREAD

**Issue by Keruspe** [CleverCloud/clever-tools#31]
Same as "clever list" but way more intuitive as we use the word "alias" everywhere

**Comment by divarvel** [comment]
list-aliases maybe?

**Comment by Keruspe** [comment]
Hmm, taking git as an example, theere is no "git list-remotes" or "git list-branches", but just "git remote" and "git branch"

But maybe those could just be... aliases of the list command?

**Comment by urcadox** [comment]
I agree with @keruspe, `clever list` is not self explanatory. Something like `clever aliases` or `clever applications` seems better.

**Comment by divarvel** [comment]
Clever applications ok
