### ISSUE TITLE
[ERROR] HTTP Error: 401 Authorization Required

### ISSUE THREAD

**Issue by mozgbrasil** [CleverCloud/clever-tools#310]
Hello

Good Morning

I'm running the command

      clever deploy

And the mentioned error is being returned

Can you help me ?

![Captura de tela de 2019-03-12 21-22-37](https://user-images.githubusercontent.com/17202780/54244801-00186180-450d-11e9-95a5-2eb380909c90.png)

**Comment by urcadox** [comment]
Hello,

Can you send a message through the interface in the console or send an e-mail to support@clever-cloud.com?

Thanks,
