### ISSUE TITLE
`clever deploy` and `clever restart` do not exit

### ISSUE THREAD

**Issue by rclement** [CleverCloud/clever-tools#318]
I am currently trying to automate my deployments with CleverCloud.

With `clever-tools` version `1.4.1`, both commands `clever deploy` and `clever restart` never exit even though a deployment is successful.
I manage to observe the same behavior on macOS (`homebrew`) and Linux (`npm`).

This issue seems related to #294, which was supposed to be fixed by #299.
Am I missing something?

**Comment by rclement** [comment]
Ok sorry for the noise, I cannot reproduce the issue anymore today, either when deploying locally or using a CI/CD server.
Closing this issue, feel free to reopen it.

**Comment by clementd-fretlink** [comment]
We've been observing this behaviour regularly on our CI. It's hard to reproduce as well (I used to reproduce it during three consecutive days, then it stopped, without updating clever-tools).

**Comment by urcadox** [comment]
It's not a random issue in the CLI, it's an issue with the events dispatching service.

**Comment by rclement** [comment]
Good to know this erratic behavior does not come from the CLI.

@urcadox, could you provide some more information about the resolution of the issue with the events dispatching service? (not necessarily an ETA but just so we can at least get a sense on what's going on and when, and if there is a deterministic workaround)

**Comment by urcadox** [comment]
I don't have any info for now sadly, this is a very random issue so it's hard to actually fix.

**Comment by justfortherec** [comment]
My workaround for #318 is to not use clever-tools for deployment in CI. Instead we use `git push`. AFAIU, this has exactly the behavior you want, @rclement:

* Only pushes changes
* Gives feedback if pushing works (fast-forwardable, etc)
* Does not wait for actual deployment and not show any logs.

**Comment by hsablonniere** [comment]
The fix is almost ready...

**Comment by hsablonniere** [comment]
OK this is fixed in [2.5.0](https://github.com/CleverCloud/clever-tools/blob/master/CHANGELOG.md#250-2020-05-26). We're no longer relying on the event API to detect that a deployment is finished.

This problem should not happen anymore. Sorry we took so much time to address this.
