### ISSUE TITLE
Add XXL & XXXL instances in scalability command

### ISSUE THREAD

**Issue by urcadox** [CleverCloud/clever-tools#325]
(and wherever else it is necessary)

**Comment by BlackYoup** [comment]
We will name them `2XL` and `3XL`. But couldn't we get them from the API instead of hardcoding them? Or is it just for completion that we need to hardcode them?

**Comment by urcadox** [comment]
I guess it would make sense. Completion can (and already does) make requests to the API.

How is it done in the console?

Anyway, we should probably open another issue for this.

**Comment by hsablonniere** [comment]
Fixed in latest beta
