### ISSUE TITLE
Fetching existing logs with --before and --after option keeps running endlessly

### ISSUE THREAD

**Issue by noisegrrrl** [CleverCloud/clever-tools#328]
Running for instance: `clever logs --until 2019-07-16T09:00:00.000Z --after 2019-07-16T08:00:00.000Z > prod.log` never terminates.
Expected behaviour would be the process to terminate once all logs for this time period have been extracted.

**Comment by divarvel** [comment]
In the example you gave, `--until` is silently ignored, and you have only `--after`, where non-termination is the expected behaviour

**Comment by noisegrrrl** [comment]
Copied the wrong command indeed, I meant `clever logs --before 2019-07-16T09:00:00.000Z --after 2019-07-16T08:00:00.000Z > prod.log`

**Comment by divarvel** [comment]
Indeed. For lines coming from the websocket connections, there is just a filter, but the stream is not closed

**Comment by pdesoyres-cc** [comment]
Closing as it is resolved by the V4 logs API
