### ISSUE TITLE
Set build instance size

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/clever-tools#331]
It could be done within `clever scale`. I can provide a patch for this change.

**Comment by urcadox** [comment]
We should probably create a new command like `settings` or something at some point, but this option does make sense in the `scale` command IMO.

@hsablonniere WDYT?

**Comment by hsablonniere** [comment]
Isn't it related to this https://github.com/CleverCloud/clever-tools/issues/74 ?

**Comment by hsablonniere** [comment]
I'm also considering `clever scale`, I'll think about it.

**Comment by divarvel** [comment]
Oh right, I forgot this issue (build flavor was not editable back then, though).

**Comment by hsablonniere** [comment]
Indeed.

**Comment by clementd-fretlink** [comment]
I'll start working on the feature itself, choosing the associated command can be done later

**Comment by hsablonniere** [comment]
Fixed in latest beta. I also added the information in `clever status`;
