### ISSUE TITLE
Log commit sha1 when doing clever deploy

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#333]
Right now we have this:

```
Pushing source code to Clever Cloud.
Your source code has been pushed to Clever Cloud
```

We need more info like the commit sha1.

**Comment by hsablonniere** [comment]
* Is this too verbose?
* Is this confusing?

![Capture d’écran_2019-09-05_17-56-32](https://user-images.githubusercontent.com/236342/64358307-85855600-d006-11e9-8a23-a601bd95d769.png)

**Comment by KannarFr** [comment]
Neat!

**Comment by divarvel** [comment]
That would be really nice to have imo (as well as in `clever status` and in
the console

**Comment by hsablonniere** [comment]
@divarvel `clever status` will also get more infos
