### ISSUE TITLE
verbose mode is broken on master

### ISSUE THREAD

**Issue by clementd-fretlink** [CleverCloud/clever-tools#335]
# Expected behaviour

adding `-v` or `--verbose` to a clever-tools call displays info and debug-level messages, as well as HTTP calls

# Actual behaviour

nothing is displayed with `-v` or `--verbose`. Setting `CLEVER_VERBOSE=1` before starting clever-tools works as expected.

# Possible cause

The application uses `process.env.CLEVER_VERBOSE` to switch to verbose mode. The env variable is then read in `src/logger.js` to act accordingly. `src/logger.js` is interpreted _before_ the code that sets `CLEVER_VERBOSE` in `bin/clever.js`. I guess it stopped working since fa5ef573a210bea9fc729178948766f92c9fe69e, where the `logger` import was hoisted at the top of the file.

**Comment by hsablonniere** [comment]
Yep sorry about that. Fixed in latest beta (https://github.com/CleverCloud/clever-tools/commit/33c51483fe36341b5456deed2c016c8b90b25aca)
