### ISSUE TITLE
Move releases to new cellar

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#339]

**Comment by BlackYoup** [comment]
- First create a new cellar add-on and bucket.
- Sync the old bucket with the new one (using `s3cmd sync` should work just fine)
- Update the CI so it uploads in the right bucket
- Update all download links

We may also want to bind the domain to our own clever-cloud.com domain to avoid any other url changes in the future.

**Comment by hsablonniere** [comment]
* [ ] update `CELLAR_CC_TOOLS_ACCESS_KEY_ID` on jenkins
* [ ] update `CELLAR_CC_TOOLS_SECRET_ACCESS_KEY` on jenkins

**Comment by hsablonniere** [comment]
https://github.com/CleverCloud/clever-tools/tree/new-cellar
