### ISSUE TITLE
--redeploy tries to push current branch instead of just redeploying the app

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-tools#34]
How to reproduce:

Push a specific branch foo
change branch to bar
clever deploy --redeploy will push bar instead of redeploying foo

**Comment by divarvel** [comment]
Since fixing #35 will add a `clever start` command, I think I'll just move `--redeploy` to a command of its own.

**Comment by Keruspe** [comment]
@divarvel makes sense

**Comment by BlackYoup** [comment]
+1
