### ISSUE TITLE
New command to read accesslogs of an application

### ISSUE THREAD

**Issue by urcadox** [CleverCloud/clever-tools#360]
Now that accesslogs are available to the users in Warp10, we could add a command in clever-tools to make this easier.
It would need to first get a Warp10 token from the API and then query Warp10.
About the API, I guess something like this would be fine:

 - `clever accesslogs --since <date> --until <date> --limit <number>`
 - `clever accesslogs --follow` (`-f` for short)

The follow feature may not be that useful and may not be so trivial to implement without dumping multiple-seconds batches all at once in the console, so I'm not sure that we should do it, not at first at least. The actually useful feature is the since/until one, it seems to me.

**Comment by hsablonniere** [comment]
Do we have an idea of the format people expect for such kind of things? We do have a lot of details in Warp10.

**Comment by divarvel** [comment]
CLF support seems a good option (https://en.wikipedia.org/wiki/Common_Log_Format) for starters

**Comment by urcadox** [comment]
I'm working on a PR for this.

Here are the formats and defaults for before / after I went with:

### Formats

#### simple
```
2020-02-07T14:00:00+01:00 92.184.110.25 GET /ping
```

#### extended
```
2020-02-07T14:00:00+01:00 [ 92.184.110.25 - Bordeaux, FR ] GET console.clever-cloud.com /ping 304
```

#### clf
```
92.184.110.25 - - [07/Feb/2020:14:00:00 +0100] "GET /ping -" 304 203
```

#### json
```
{"t":"2020-02-07T13:00:00.146987Z","a":"app_1246f211-d4a7-4787-ba62-56c163a8b4ef","adc":"clevercloud-adc-n6","o":"orga_858600a8-74f4-4d75-a8a3-f5b868be093c","i":"f9ed5548-b196-4da5-9243-645a9c3a5e94","ipS":"92.184.110.25","pS":43341,"s":{"lt":44.8412,"lg":-0.5806,"ct":"Bordeaux","co":"FR"},"ipD":"46.252.181.39","pD":14721,"d":{"lt":48.7967,"lg":2.3338,"ct":"Cachan","co":"FR"},"vb":"GET","path":"/ping","bIn":926,"bOut":203,"h":"console.clever-cloud.com","rTime":"62ms","sTime":"81μs","scheme":"HTTPS","sC":304,"sT":"Not Modified","w":"WRK-00","r":"82cb0eb4-c4b5-4115-8f41-ee4b9a252ae7"}
```

A user can always pick the `json` format and output what they want with `jq`.

### Defaults for before/after

 - Both undefined: return the last hour of logs
 - After undefined: return 1 hour of logs before the `before` timestamp
 - Before undefined: return all the logs from the `after` timestamp up until now

Any thoughts about this?
