### ISSUE TITLE
Deploy: option to continue logs streaming after the deployment is done

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-tools#375]
My use case here is that I usually do `clever deploy && clever logs` to follow logs after a deployment has occurred. Maybe we could add an option to continue following logs after a deployment has succeeded ? In case of deployment failure, logs should stop.

Would it make sense?

**Comment by hsablonniere** [comment]
OK, I have something. Can we agree on the naming?

* `--follow`
* `--continue-logs`
* `--keep-logs`
* ...

Do we need a shorthand param?

**Comment by hsablonniere** [comment]
BTW, we agreed on `--follow`.
