### ISSUE TITLE
clever scale --build-flavor disabled: you provided invalid application data

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-tools#378]
The help of `clever scale --help` shows that to disable the build instance, you have to pass `disabled`: `clever scare --build-flavor disabled`

But when I do this, it throws an error:
```
~ $ clever scale --build-flavor disabled
[ERROR] You provided invalid application data
```

**Comment by divarvel** [comment]
There's an issue in the request that's sent to the API. The help text is accurate

**Comment by hsablonniere** [comment]
@divarvel Thanks to your feedback and PR, we investigated and managed to simplify the code and do everything in one call. See PR #380.
