### ISSUE TITLE
Handle some "human relative dates" in logs and accesslogs

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#382]
Something like "1 hour ago"...

* Other examples?
* Are there any libs we can use for this?

poke @urcadox @KannarFr

**Comment by hsablonniere** [comment]
https://www.gnu.org/software/coreutils/manual/html_node/Date-input-formats.html#Date-input-formats

**Comment by hsablonniere** [comment]
* https://github.com/derhuerst/parse-human-relative-time
* https://github.com/cmaurer/relative.time.parser
* https://github.com/alanclarke/parse-human-date
* https://github.com/sonirico/datetoken.js
* https://github.com/AdvancedClimateSystems/moment-relativism

**Comment by pdesoyres-cc** [comment]
Closing as is resolved by https://github.com/CleverCloud/clever-tools/pull/609
