### ISSUE TITLE
clever login / logout doesn't login / logout

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-tools#394]
Experienced both on windows and Linux.
The `clever-cloud` config file isn't written (or deleted in case of `clever logout`), no error happens. Using `clever login --token <token> --secret <secret>` doesn't work either. Only environment variables work fine (`CLEVER_TOKEN` and `CLEVER_SECRET`).

A customer reported the issue on Windows using clever-tools 2.2.1. I tried to reproduce on Linux but it worked fine until I saw that I was using version 2.2.0. After upgrading to version 2.2.1, I had the same issue and couldn't login anymore.

**Comment by hsablonniere** [comment]
Report:

* In 2.0.0, we updated a dep call `mkdirp`.
* This new version returns a promise instead of using a node callback API
* We forgot to update the code using this (used in `clever login` and `clever logout`)
