### ISSUE TITLE
"The provided application id doesn't belong to you" with 2.2.1+

### ISSUE THREAD

**Issue by hgwood** [CleverCloud/clever-tools#397]
Hello Clever Cloud 🙂

My CI pipeline started failing on Friday when deploying, more precisely when running `clever link [app_id]` with the error `The provided application id doesn't belong to you`. 

I've reproduce the error locally and found it occurs only using clever-tools 2.2.1 or 2.2.2. So as a workaround, I'll be pinning the version to 2.2.0 for CI.

I'm going to start digging in the code of clever-tools to see what I can find...OK just checked and  PR #396 was just submitted 2 minutes ago to "fix clever link" so maybe that will do, I'll test it.

Thanks for the great tools!

**Comment by hgwood** [comment]
Can confirm #396 fixes the issue!

**Comment by hsablonniere** [comment]
Hey @hgwood, thanks for the report, we're discussion a detail about this and will be back with a fix very very soon :wink: Sorry for this bug and for the delay.

**Comment by hsablonniere** [comment]
Fixed in 2.2.3 ;-)
