### ISSUE TITLE
/bin/env not found in postinstall.sh

### ISSUE THREAD

**Issue by rdalverny** [CleverCloud/clever-tools#4]
In `scripts/`, `postinstall.sh` uses `/bin/env sh` as an interpreter (and breaks, at least on OSX), whereas the two other scripts use `/usr/bin/env sh`. Is there are specific reason for the difference?

**Comment by divarvel** [comment]
Me being stupid. Fixed in 0e88c6ef85cd5c7dedf2cd47778ac45817f38989
