### ISSUE TITLE
Add a simpler way to use another API endpoint

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#410]
Right now, you can use the CLI to query the preproduction env but you need to have it locally and play with inner config :-(

**Comment by divarvel** [comment]
If you set the `API_HOST` environment variable, it doesn't work?

https://github.com/CleverCloud/clever-tools/blob/master/src/models/configuration.js#L57

`getOrElseAll` is supposed to read values from the environment and default on the provided values if they are not in the environment

**Comment by hsablonniere** [comment]
Thanks @divarvel, you're right. This is a "duplicate" of #345 somehow.
