### ISSUE TITLE
Only show logs of the currently deploying instances in `clever deploy` and `clever restart`

### ISSUE THREAD

**Issue by leonard-IMBERT** [CleverCloud/clever-tools#42]
When you have a lot of log per minutes it pollute your deployment logs. I think it can be usefull to show only the log of the deploying instance or at least make it as an option

**Comment by divarvel** [comment]
Yes, it's planned.

**Comment by divarvel** [comment]
It's not feasible yet though, we don't know which instance ids are in a given deployment (that could change during a deployment, when new instances pop up or are powered down).

When the logs track the deployment id, then we'll be able to do that.
