### ISSUE TITLE
Let the user know that a deployment will start after the push occured

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-tools#428]
The CLI currently displays those logs once the push has been done:
```
Your source code has been pushed to Clever Cloud.
Deployment started (deployment_xxx)
```

A log saying that a deployment will soon start right after the first line should be added because deployments are asynchronous which means they can take a few seconds or a few minutes to start after the push happened.

**Comment by hsablonniere** [comment]
Released in https://github.com/CleverCloud/clever-tools/releases/tag/2.7.0 https://github.com/CleverCloud/clever-tools/blob/master/CHANGELOG.md#270-2020-08-20
