### ISSUE TITLE
Output of old logs is limited to 1000 lines

### ISSUE THREAD

**Issue by blalasaadri** [CleverCloud/clever-tools#429]
As is mentioned in [this reply to issue 403](https://github.com/CleverCloud/clever-tools/issues/403#issuecomment-647354149), when fetching logs with `--after` / `--since` only 1000 lines are printed. This is especially annoying, since there doesn't seem to be another way to say _"Give me all logs from the following deployment"_ - which can sometimes be really useful. (Also, what I would expect the _"DOWNLOAD LOGS"_ button in the console to do... but that's a different issue.)
From looking at the [clever-client.js](https://github.com/CleverCloud/clever-client.js) project, I believe that the problem here is with the REST API which delivers the logs.

**Comment by hsablonniere** [comment]
@blalasaadri You're exactly right, this limitation comes from the way the API answers. We're considering fetching logs in batches but @KannarFr is also working on an update of the logs system so I'm waiting on this to move forward.

**Comment by agueganno** [comment]
Do you have any update on this one ? I need to check logs from yesterday but don’t have a proper way to do it. Is scrolling in the console the only way, really ? :-(

**Comment by pdesoyres-cc** [comment]
@blalasaadri with the improvements we made on the API and the CLI, you are no longer limited to 1000 lines of logs. 

By the way, we have also reworked the logs page in the Console.

I'm closing this issue since the problem should be resolved now.
