### ISSUE TITLE
No way to retrieve deployment IDs

### ISSUE THREAD

**Issue by blalasaadri** [CleverCloud/clever-tools#430]
In some commands (e.g. `clever logs --deployment-id DEPLOYMENT_ID`), you are supposed to pass a deployment ID. However, I couldn't find any way of retrieving that via the clever tools; in fact, even in the console the only place I've been able to find them so far are by manually parsing the _Logs_ links in the _Activity_ view.
I would expect to find the deployment IDs when calling `clever activity` - though hopefully with table headers, since with the current view, you have to just know / guess that it's:

Activity start time | Activity result status | Activity type | Commit ID | Activity trigger
------------ | ------------- | ------------ | ------------- | -------------

I'm running all of this in clever-tools 2.6.1.

**Comment by hsablonniere** [comment]
That's something I also considered, thanks for the issue :wink:
