### ISSUE TITLE
Clever deploy: no log / error message if ssh key is not registered on the SSH Agent 

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-tools#44]
When my key is not yet added to an ssh-agent, ``clever deploy`` will not output any information and just "wait" instead of telling me to add my key first

**Comment by jtanguy** [comment]
Part of a solution could be to check the ssh agent via `ssh-add -l`, but then you'd have to check that one of the keys currently in the agent can authenticate the user.

**Comment by divarvel** [comment]
The CLI tool will soon use HTTPs auth for git, which will solve all the ssh-related issues
