### ISSUE TITLE
Get addon environnement variable from clevercli

### ISSUE THREAD

**Issue by Grounz** [CleverCloud/clever-tools#446]
Hi,

With clever-tools cli we want get environnement variable and configuration of AddOn installed in organisation.

The clever-tools can just create/list/delete addon-on but not print configuration and environnement variable for addon.

My use case is the next:

- In the CI/CD we want create many addon (pulsar, mongodb), we use ansible + clever-tools. After creation of addon we want get with clever-tools the environnement variable from addon (uri, password, token,), in the goals of share their configurations with application deployed by ci/cd which consumme their addons.

And if it's possible to have an output in json format.

**Comment by hsablonniere** [comment]
I'm closing this as this is very close to #424.
