### ISSUE TITLE
Kill `clever ng join` running sub-process on `clever ng leave`

### ISSUE THREAD

**Issue by RemiBardon** [CleverCloud/clever-tools#458]
## Context

When a user joins a networkgroup (`clever ng join`) with a first terminal, it hangs and wait for a `SIGINT`/`SIGTERM` signal.

## Problem

If they don't close this first terminal, and run `clever ng leave` in a second one, it makes them leave the networkgroup and remove all configuration files.

If they now leave from the first terminal (e.g. <kbd>Ctrl</kbd>+<kbd>C</kbd>), they will have errors.

## Proposed solutions

1. **Elegant but risky:** When the user leaves from terminal 2, kill the process running in terminal 1. It might cause problems where a user automated these commands. Also, how to get the PID, and would it be possible to store the `clever ng join` sub-process PID somewhere (would store another thing on the device 😕)?
2. **Safe but not great:** Silently leave if errors occur (files not found).
3. **Balanced solution:** Show error messages if errors occur on leave, but add informational message saying it might be normal if user left from another terminal.

**Comment by Keruspe** [comment]
What about not hanging in join, just joining and exit, and require an explicit leave?

**Comment by RemiBardon** [comment]
Yeah, could do it too, now that we have a `clever ng leave` command 💁🏻‍♂️

@hsablonniere What do you think?

**Comment by RemiBardon** [comment]
So a process would listen to the configuration SSE in the background?

**Comment by RemiBardon** [comment]
Btw, I just realize I should add a security to avoid joining a networkgroup twice 💡
