### ISSUE TITLE
CC_DOCKERFILE environment variable not being used

### ISSUE THREAD

**Issue by ticapix** [CleverCloud/clever-tools#484]
Hi,

I have a repository with 2 Dockerfile inside and I would like to deploy the 2 applications with `clever deploy` version `2.8.0`.

Following the documentation https://www.clever-cloud.com/doc/reference/reference-environment-variables/#docker I'm using the variable `CC_DOCKERFILE`

```shell
export CC_DOCKERFILE=Dockerfile-frontend
clever deploy
```

The expected result would be the deployment of the application, however I'm getting the following error:
```
Error: mandatory Dockerfile named 'Dockerfile' not found. Please provide one and redeploy
```

And I don't see any `Inject CC_DOCKERFILE` in the log.

Am I missing something ?

Thank you very much,
Pierre

**Comment by gaelreyrol** [comment]
You need to add this environment variable in the environment variables of your application in the console, not locally :slightly_smiling_face: 

Please recreate this issue in [this repository](https://github.com/CleverCloud/doc.clever-cloud.com/) if you think it is still relevant.

**Comment by ticapix** [comment]
perfect, thanks !
