### ISSUE TITLE
Fix docker hub publication

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#511]
* [x] Publish 2.9.0 manually on docker hub
* [x] Restore the automated build based on GitHub (or something else)

**Comment by nsteinmetz** [comment]
Hi @hsablonniere 

If you could push 2.10.1 images too, it would be nice !

We are stucked with 2.9.1 images for a year.

**Comment by hsablonniere** [comment]
@nsteinmetz Sorry about this one.

**Comment by hsablonniere** [comment]
@nsteinmetz 2.10.1 is on dockerhub :heavy_check_mark:

**Comment by nsteinmetz** [comment]
@hsablonniere thanks a lot !

**Comment by pdesoyres-cc** [comment]
closing as resolved by https://github.com/CleverCloud/clever-tools/pull/675
