### ISSUE TITLE
Add a command to build then deploy

### ISSUE THREAD

**Issue by alexislefebvre** [CleverCloud/clever-tools#528]
We deployed a Next application on Clever Cloud. The content is managed in a CMS, the app read the content and generate a website. After updating the content in the CMS, a webhook trigger a job in our CI, which deploy the website. It works on Vercel but not on Clever Cloud:

We need to trigger build and deploy to see changes, but today we can only trigger builds if a new commit is pushed, so our CI can't automatically launch a new build after the webhook has been called.

**Comment by alexislefebvre** [comment]
Current workaround: create a fake commit on the CI then push it:

```yaml
    - touch .deploy
    - git add .deploy
    - git config --global user.email "ci@gitlab.…"
    - git config --global user.name "GitLab CI"
    - git commit --message "deploy"
    - git push clevercloud HEAD:master --force
```

**Comment by divarvel** [comment]
You can use `clever restart --without-cache`

This will trigger a rebuild even when there are no changes in git

**Comment by alexislefebvre** [comment]
@divarvel It worked as expected, thanks!
