### ISSUE TITLE
release.md at the "Automated releases" chapter is missing

### ISSUE THREAD

**Issue by sirchamallow** [CleverCloud/clever-tools#548]
At the [Automated releases](https://www.clever-cloud.com/doc/getting-started/cli/#automated-releases) part,

> This project uses Jenkins to build binaries, package them and release them automatically on the various repositories. If you want to know more or if you need to release a new version, please read [RELEASE.md](https://www.clever-cloud.com/doc/getting-started/cli/RELEASE.md) carefully.

The file release.md is missing. If you click on file : 

"Not Found
The requested URL was not found on this server."

**Comment by Bencaddyro** [comment]
Right now automated release is broken, @s0dyy will take a look on it next week
