### ISSUE TITLE
[FEAT] Allow manage config-provider content over CLI

### ISSUE THREAD

**Issue by chmuche** [CleverCloud/clever-tools#553]
Hello,

I wonder if it's possible to set env variable on the addon `config-provider` with the cli.

I'm thinking of something like adding an argument `--config <config_id>` on the command `clever env`.

**Comment by miton18** [comment]
Hi @chmuche , sorry for the late response

It's doable while not very user friendly.

```
❯ clever curl -X PUT "https://api.clever-cloud.com/v4/addon-providers/config-provider/addons/config_f387e5e5-976b-4bb7-8dc8-01e814d3a5fd/env" -H "Content-Type: application/json" -d '[{"name": "MY_KEY", "value": "my_val"}]'
```

**Comment by chmuche** [comment]
Thanks, for the answer.

This is exactly what I do :+1:
