### ISSUE TITLE
Deployed broken when project name contain :: chars

### ISSUE THREAD

**Issue by GuillaumeASSIER** [CleverCloud/clever-tools#562]
Hi,

I noticed that the CLI seemed to be broken when trying to deploy a project which has a name containing `::` chars.

```shell
[sykursen@fedora ecchymose]$ clever deploy
[ERROR] "guillaume::ecchymose" would be an invalid git reference. (Hint: a valid alternative would be "guillaume--ecchymose".)
```

**Comment by hsablonniere** [comment]
I don't understand, where did you use `guillaume::ecchymose`? It's not a valid git branch name so I don't get how a `clever deploy` would try this.

**Comment by Sykursen** [comment]
I am using `guillaume::ecchymose` as application name on the clever-cloud platform. After creating my application, I try to deploy it with clever-tools and I get this error during the deploy command. After renaming the application name in `.clever.json` without `::` the deploy command worked again.
