### ISSUE TITLE
List clever curl in command help

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#615]

**Comment by davlgd** [comment]
In the help, after the available commands, we could add (for example) : 

>>>
...
webhooks                   Manage webhooks

Need to go further ? Once logged in, you can use clever-tools to easily query our API through 'clever curl' command. For example : 

clever curl https://api.clever-cloud.com/v2/organisations
clever curl https://api.clever-cloud.com/v2/organisations/<YOUR ID>/applications | jq '.[].id'

Our API documentation is available here : https://www.clever-cloud.com/doc/openapi
Tell us more about what you need for Clever tools : <short feedback URL>
>>>

**Comment by davlgd** [comment]
Note that `clever curl --help` prints an bad help message in french : 

```
clever curl --help
Options :
  --help     Affiche l'aide                                            [booléen]
  --version  Affiche le numéro de version                              [booléen]
```

If you type `clever curl --version` the answer is the clever-tools version number

**Comment by hsablonniere** [comment]
@davlgd We like your of showing examples for clever curl but only with `clever curl --help`.

FYI: right now, we have no idea why there's some french prompt with `clever curl --help`.

**Comment by chmuche** [comment]
It's possible to shortcut the URL too?

`clever curl https://api.clever-cloud.com/v2/self` by `clever curl /v2/self`
Your url is always the same, no ? Maybe with on Premise it's not the case. :man_shrugging: 

Can we do something like 
if the url start with `/` then we add the env var `CC_TOOLS_API_ENDPOINT` or `https://api.clever-cloud.com`

**Comment by chmuche** [comment]
@davlgd You Mention 

`clever curl https://api.clever-cloud.com/v4/billing/organisations/<YOUR_ID>/invoices`

but I can't find this endpoint on de openAPI

https://www.clever-cloud.com/doc/openapi
or
https://developers.clever-cloud.com/openapi/

This exactly what I need to automatically integrate the invoice inside our accounting software.

Thanks :heart:

**Comment by davlgd** [comment]
The main concept of `clever curl` command is to allow to use `curl` "as-is" in a Clever Cloud authed context. I'm not sure we want to start to modify the request on the fly. 

About v4/billing endpoints, public documentation step is coming soon ;)

**Comment by pdesoyres-cc** [comment]
Closing this issue as fixed by https://github.com/CleverCloud/clever-tools/pull/632
