### ISSUE TITLE
clever create : optional app name

### ISSUE THREAD

**Issue by davlgd** [CleverCloud/clever-tools#616]
Currently, to create an app, we need to declare its name: 

`clever create -t <app_type> <app_name>`

It could be simpler if this parameter became optional. We could use the current folder name as the default app name and change the "human" message from : 

>Your application has been successfully created!

to 

>Your application has been successfully created as 'app_name'!

**Comment by hsablonniere** [comment]
@miton18 idea:

* by default: a confirmation prompt with the current dir
* an option to auto confirm the current dir as name

We would detect the interactive ability of the current shell to maybe error and not prompt if it's useless.
