### ISSUE TITLE
clever create --task 

### ISSUE THREAD

**Issue by davlgd** [CleverCloud/clever-tools#629]
To create a task a user need to know it exists and add manually `CC_TASK=true`. It could be great to create en app as a task with a `--task` flag detailed in the helper. It can be done through the API with the parameter `instanceLifetime` set to `TASK`

**Comment by chmuche** [comment]
Maybe the flag `--task` can be an argument to set the env var `CC_TASK_SCRIPT`

To create an application
`clever create <app_name> -o orga_xxxxx --type=python ....` then almost always `clever scale` to choose the plan

To create an add-on
`clever addon create <addon_provider> <addon_name> -p <addon_plan>`

To create a task
`clever create <app_name> -o orga_xxxxx --type=python --task=/my_script/path.py`

**Comment by davlgd** [comment]
The env var used for a task is `CC_RUN_COMMAND`, but maybe we can define it directly with a `--task COMMAND`.
