### ISSUE TITLE
clever addon create: use cheapest/lowest plan by default

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#653]
## Context

Right now `clever addon create` uses `dev` plan by default when not specified, it only works for PG and MySQL. We should use the cheapest/lowest plan by default.

**Comment by pdesoyres-cc** [comment]
@hsablonniere 
If we don't use a free plan by default, should we notify the user which plan will be used, and how much it costs? Should we ask for confirmation?
