### ISSUE TITLE
Deployment logs fail with `[ERROR] Internal server error`

### ISSUE THREAD

**Issue by florian-sanders-cc** [CleverCloud/clever-tools#671]
## Context

After using the command `clever deploy -a my-alias -f`, during a deployment, I got the following error and the logs stopped:
`[ERROR] Internal server error`

The deployment was successful, only the logs were stopped within the terminal.

## Debug info

Here is the result of `clever diag`

> clever-tools  3.1.0
> Node.js       v18.15.0
> Platform      linux
> Release       6.7.2-arch1-1
> Architecture  x64
> Linux         Arch Linux
> Shell         /usr/bin/fish
> Packaged      true
> Exec path     /usr/bin/clever
> Config file   /home/flo/.config/clever-cloud/clever-tools.json
> Auth source   configuration file

**Comment by hsablonniere** [comment]
Thanks @florian-sanders-cc , I think this is fixed, can you reopen if you still have the problem?
