### ISSUE TITLE
Do we use `CI_CLEVER_CLOUD_SSH_KEY`?

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#676]
@pdesoyres-cc The RELEASE.md mentions the variable `CI_CLEVER_CLOUD_SSH_KEY` but I cannot find it in the repo, are we using this?

**Comment by pdesoyres-cc** [comment]
No, we don't so the documentation is wrong.

However, `SSH_PRIVATE_KEY` secret is used in the publish action, but this is not quite the same thing:
- it is not used through env var
- it is used only for the CI to make it have write access on the targeted repositories.

Indeed, people who want to publish, need to use an SSH key that grants write access to target repositories. Is this something we want to document in the `RELEASE.md` file?

**Comment by hsablonniere** [comment]
Thanks for the clarification @pdesoyres-cc :+1: 

> No, we don't so the documentation is wrong.
Can you update the RELEASE.md?

> Indeed, people who want to publish, need to use an SSH key that grants write access to target repositories. Is this something we want to document in the RELEASE.md file?
If you have a nice way to explain it, let's try. If not, it's OK like this.
