### ISSUE TITLE
[logs] support indexPrefix optional field for ElasticSearch drains

### ISSUE THREAD

**Issue by KannarFr** [CleverCloud/clever-tools#695]
The ElasticSearch drain has a default publishing index `logstash-<date>`. API has been updated to support passing `indexPrefix` to the related drain creation.

I'm willing to open a PR.

**Comment by hsablonniere** [comment]
@KannarFr You have our blessing to create a PR. @miton18 and @aurrelhebert will be available for reviews in the following weeks. Beware of the new commit style validator, new automatic linter...
