### ISSUE TITLE
Cannot fetch access logs

### ISSUE THREAD

**Issue by julienbonvarlet** [CleverCloud/clever-tools#703]
Hello,

I get an error while trying to fetch accessLogs.
The command I ran :
`clever accesslogs --alias=main`
The error :
`[ERROR] Parse Error: Invalid header value char`

Clever tools version: 3.4.0

Can you guys fix it please ? Thanks!

**Comment by miton18** [comment]
Hi @julienbonvarlet , current accesslogs are not available anymore.
We are working on a complete rewrite of the pipeline. 
Job is almost done and we expect to reopen this feature soon with much more power (infinite retention on demand, better schema, ...).
