### ISSUE TITLE
Problem with packaged CLI installed via AUR on archlinux

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#708]
This needs some investigation, well gather different environments and outcomes in this thread...

**Comment by hsablonniere** [comment]
## Test on archlinux docker container

* docker image: https://hub.docker.com/_/archlinux/tags
* docker image ID: `0cda8061254a`
* uname: `Linux 6.8.2-arch2-1 x86_64`
* install through `makepkg -si` works :ballot_box_with_check:

**Comment by sebartyr** [comment]
On clean archlinux installation:
- installed with yay or with pacman/makepkg -si
- clever diag cannot work beacause the package seems to be broken
- not in a VM
- architecture amd64_x86, kernel 6.8.x

=> `Pkg: Error reading from file.`

**Comment by aurrelhebert** [comment]
I reproduce it too:

**Comment by aurrelhebert** [comment]
The step I did: 

```sh
yay clever-tools
sha256sum /usr/bin/clever
# 505fd73e846aabaf718f42c2e4f26fd52d54a4cd6d3c778a6ba371212ce81a78  /usr/bin/clever
node --version
# v18.15.0
uname -r
# 6.8.2-arch2-1
/usr/bin/clever diag
# Pkg: Error reading from file.
```

The yay output is (sorry for French): 
```
==> Récupération des sources…
  -> clever-tools-3.4.0_linux.tar.gz trouvé
==> Validation des fichiers source avec sha256sums…
    clever-tools-3.4.0_linux.tar.gz ... Réussite
==> Suppression du répertoire $srcdir/ existant…
==> Extraction des sources…
  -> Extraction de clever-tools-3.4.0_linux.tar.gz avec bsdtar
==> Les sources sont prêtes.
==> Création du paquet clever-tools-bin 3.4.0-1 (jeu. 04 avril 2024 10:27:40)
==> Vérification des dépendances pour l’exécution…
```

**Comment by hsablonniere** [comment]
After a long investigation with @miton18 we found out that editing `options=('!strip')` into `OPTIONS=(!strip)` fixes the problem. With the bad options, makepkg was stripping some parts of the binary. We're not sure why it was working before or why it must me uppercase.
