### ISSUE TITLE
List an owner applications

### ISSUE THREAD

**Issue by aurrelhebert** [CleverCloud/clever-tools#737]
We should be able to list an owner applications. 

This is currently possible threw the following `cURL` command:

```
clever curl https://api.clever-cloud.com/v2/organisations/<owner_id>/applications | jq '.[].name'
```

**Comment by davlgd** [comment]
As discussed today, we need a way to support it in a non breaking way for now, and unify how we list things (add-ons, applications, backups, etc.) later. 

For example we could use `clever applications` in a non-linked context to show such a list, and introduce à `--list` when the user is in a linked context.
