### ISSUE TITLE
Edit application config with `clever config`

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/clever-tools#74]
For now: name, description, zero-downtime deployment, sticky sessions, dedicated build instances, cancel on push.

`clever config set name <name>`
`clever config set description <description>`
`clever config set zero-downtime (true|false)`
`clever config set sticky-sessions (true|false)`
`clever config set dedicated-build (false|<flavor>)`
`clever config set cancel-on-push (true|false)`

It could also be done with flags, but that could get messy. Thoughts?

**Comment by divarvel** [comment]
https://github.com/CleverCloud/clever-tools/tree/config

**Comment by hsablonniere** [comment]
Latest discussions on this:

* We need the upcoming feature "force-https"
* We're considering creating only one command with many optional flags like this:

```
clever config set --name <name> --description <description> --zero-downtime (true|false) --sticky-sessions (true|false) --dedicated-build (false|<flavor>) --cancel-on-push (true|false) --force-https (true|false)
```

@divarvel Do you remember why flags could get messy?

@Keruspe poke

@urcadox You had an opinion about this?

**Comment by hsablonniere** [comment]
What this proposition means:

```
clever config set name <name>
clever config set dedicated-build (false|<flavor>)
...
```

* new `clever config` command
* a `clever config set` sub command with first param being the name of the option and second param being the value
* you need several command calls (thus multiple REST calls) to apply multiple config modifications

**Comment by hsablonniere** [comment]
Also: maybe it's a good opportunity to get/display the current config too.

**Comment by hsablonniere** [comment]
So even if we set on flats, we should create a `get` subcommand and a `set` subcommand.

**Comment by hsablonniere** [comment]
I guess the `clever env set name value` makes more sense when you consider the `get` equivalent which could be used to retrieve just on option in a script into a var.

**Comment by urcadox** [comment]
I'm partial to not using flags (i.e. an API similar to the examples given by @divarvel).

I only see one positive thing with flags: you can set multiple config items at once. It can be nice in a CI context or to give a one-liner in a blog post / documentation.

I see multiple (potentially) negative things with flags:

 - Error handling will be more painful
 - What would the output of the get command counterpart look like when you provide multiple flags?
 - Autocompletion may be trickier to implement / not as pleasant to use
 - Won't config items end up using different API endpoints? Will that not be annoying to implement when multiple flags are set at once?

Are there more positive things I'm not seeing? Would it be easier to implement / maintain maybe?

**Comment by hsablonniere** [comment]
_Hubert was convinced by his awesome colleagues... :hugs:_

**Comment by Keruspe** [comment]
Random brain dump:

```
# Display the current config
clever config [get] [config-name]
# Set a single configuration
clever config set <config-name> <config-value>
# Set multiple configurations
clever config update [flags]
```

Examples:
```
clever config
clever config get force-https
clever config set force-https true
clever config set dedicated-build true --build-flavour=S
clever config update --enable-force-https --disable-sticky-sessions --enable-dedicated-build --with-build-flavour=S
```

**Comment by hsablonniere** [comment]
About the dedicated build, we may not implement it here because it's already available in `clever scale`.

**Comment by Keruspe** [comment]
@urcadox most of these flags can be edited in a single rest endpoint

**Comment by urcadox** [comment]
> @urcadox most of these flags can be edited in a single rest endpoint

**Comment by divarvel** [comment]
@hsablonniere about flag being potentially messy: with arguments, the option name parsing can be handled in the `command` module (this allows more flexibility, even remote fetching, etc). otoh, flags need to be hardcoded in the parser, so they need to be kept in sync with the implementation.

For multiple modifications, it can be done with arguments, but that would require some kind of ad hoc syntax (eg `key=value`).

Apart from multiple modifications, one benefit I see with flags is that they would be more discoverable (all possibilities show up in the output of `--help`).

**Comment by clementd-fretlink** [comment]
I've had a look at what @Keruspe did: generating parser bits from the command module: that's what I would have done as well
