### ISSUE TITLE
Mongodb dev plan can still be created

### ISSUE THREAD

**Issue by Kirbeerus** [CleverCloud/clever-tools#800]
Using the CLI, it is possible to create MongoDB DEV plan even thought clever cloud doesn't have this plan for mongo anymore

Command used :  
`clever addon create mongodb-addon --plan dev testmongo`

**Comment by miton18** [comment]
Thanks, I will take a look

**Comment by aurrelhebert** [comment]
Fixed! Thanks for the catch :heart:
