### ISSUE TITLE
clever unlink not working

### ISSUE THREAD

**Issue by maxime-menant** [CleverCloud/clever-tools#81]
Hi!

I tried to unlink an application I deleted from the web dashboard using 

```clever unlink app_58fc0dc3-04e7-4045-8416-95a3317a4a14```

but when I run `clever applications` the app is still here.

```
$ clever applications
Application ——
  alias: ——
  id: app_58fc0dc3-04e7-4045-8416-95a3317a4a14
  deployment url: ——

Application ——
  alias: ——
  id: app_cea68d53-65e2-41e2-82fe-7fe95805b887
  deployment url: ——
```

`clever status`is also saying to use a command that do not exist `clever list`

```
$ clever status
[ERROR] Several applications are linked. You can specify one with the `--alias` option. Run `clever list` to list linked applications. Available aliases: ——, ——
```

**Comment by urcadox** [comment]
`clever unlink` takes the application alias, not the ID.

I guess it would make sense for it to work with the ID as well. What do you think @clementd?

I will make a separate issue for the `clever list` mention.

**Comment by maxime-menant** [comment]
Maybe you should change the behavior of the command unlink indeed, because both apps had the same alias so using the ID seemed logic for me '^^

and the return of the command is also wrong by the way since it said
```
$ clever unlink app_58fc0dc3-04e7-4045-8416-95a3317a4a14
Your application has been successfully unlinked!
```
