### ISSUE TITLE
Rework the alias behaviour

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/clever-tools#83]
Right now, aliases are used to select an application among the linked application.

A possible replacement:
- remove `--alias`
- replace it with `--application`, which can be an `app_id`, the application name, or an alias
  Using the `app_id` would allow to disambiguate the linked applications if they have the same name or alias (but the alias would still be the recommended way to disambiguate, as well as being the most convenient)

See #81

**Comment by divarvel** [comment]
poke @judu @urcadox @BlackYoup

**Comment by urcadox** [comment]
Your suggestion looks really good to me. I guess we could sum up the input by whatever-the-link-command-can-take-as-input or an alias.

**Comment by ndeloof** [comment]
I'd like to be able to run all clever CLI commands with plain application ID, and as a local (?) shortcut define some aliases. Would maybe be even simpler to just be able to use my organisationID/applicationName as an implicit alias

**Comment by divarvel** [comment]
So:

You can run every command with
- `--application <app_id>`
- `--application <app name> --organisation <organisation name (or id)>`

If you link the application
- `--application <alias>`
- `<nothing>` (if the application is set as default or is the only one available)

**Comment by ndeloof** [comment]
oh really, didn't know. Seems my brain is trying to get the same syntax I used to type for `bees` SDK commands.

**Comment by ndeloof** [comment]
@divarvel doesn't seem to work

```
# clever restart --without-cache --organisation cfp.io --application front-legacy
[ERROR] There are no applications linked. You can add one with `clever link`
```

maybe just an error reporting issue ? I have the same error if I use a non-existent org or application name

**Comment by ndeloof** [comment]
even worse : if I have a linked application, this one is restarted and not the one I point to
```
clever restart --without-cache --organisation cfp.io --application front-legacy
Restarting callForPapers without using cache
Waiting for application logs…
...
```

**Comment by divarvel** [comment]
I wasn't clear in the previous message, I wasn't describing current behaviour, but the desired one

**Comment by ndeloof** [comment]
oh ok, sorry for that.

**Comment by clementd-fretlink** [comment]
Is this still considered? Would an external contribution make sense?

**Comment by urcadox** [comment]
I don't have any objection.

@hsablonniere can we have your input?

**Comment by aurrelhebert** [comment]
Resuming:
  - Make clever link optional and allow appId on all commands:
    - Which commands? 
    - AppId place in a command? For example it could the first argument
  - What about orgaId?

**Comment by divarvel** [comment]
https://github.com/CleverCloud/clever-tools/issues/83#issuecomment-303703555

**Comment by hsablonniere** [comment]
It will be in the next release!
