### ISSUE TITLE
Support for webhooks

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/clever-tools#84]
Webhooks can be registered on the notification API, each webhook has the following shape:

```
{
   owner_id: <user_id> or <org_id>, // the owner of the hook (user or organisation)
   urls: [ {body_format: "raw" or "slack", url: <url>], // one or more URLs to call when events happen
   scope: [<user_id or org_id or app_id or addon_id>],// the entities we're interested in
   events: [<event type>] // the events we're interested in
}
```
It's a bit hard to map that to a CLI interface without ending up with something bloated, so I think the best way is to find a subset that can be cleanly mapped to a cli interface, eg

```
# list the active notifications
clever notifications [--org <org_id>]

# create a hook with only one url
clever notifications [--org <org_id>] add \
   [--format <format>] \ # default: raw
   [--event <event_type>] \ # array, nothing means all events
   [--entity <app / addon>] \ #array, nothing means the whole owner
   <url>

# remove a hook
clever notifications [--org <org_id>] remove <hook_id>
```

It's in no way complete, but it's a good starting point. Thoughts @urcadox @BlackYoup ?

**Comment by urcadox** [comment]
Just a little clarification: scope can only contain a list of applications and addons. If a hook is owned by a user, it will only match events coming from applications and addons owned by this user, not the ones owned by one of their organisations.

I would either rename entity to entities or events to event. It depends if you want something like `clever notifications --format slack --event DEPLOYMENT_SUCCESS --event DEPLOYMENT_FAIL --entity app_xxx --entity app_yyy https://hooks.slack.com/zzzzzzz` or something like `--events "DEPLOYMENT_SUCCESS,DEPLOYMENTFAIL"`.

I guess not many CLIs have arrays as parameters, I'm not sure what is the most common.

**Comment by divarvel** [comment]
I've updated the issue according to your remarks

**Comment by divarvel** [comment]
See the `notifications` branch: https://github.com/CleverCloud/clever-tools/tree/notifications
