### ISSUE TITLE
Issue with clever domain overview and wildcard domains.

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#847]
We get this error with wildcard domains `*.example.com`

```
[ERROR] Cannot read properties of null (reading 'split')
```

**Comment by florian-sanders-cc** [comment]
As discussed, we'll go with the `validateHostname: false` (see https://github.com/remusao/tldts/issues/1246 for more info) because hostnames have already been validated and we don't need to be that strict in our context.
